#   ubuntu based nvidia sdk NVHPC GPU Utilization
#
#
#

FROM fje1223/spel_baseos_nvhpc
LABEL maintainer.name="Franklin J Eaglebarger" \
      maintainer.email="fye@ornl.gov" \
      author.name="Franklin J Eaglebarger" \
      author.email="fye@ornl.gov" \
      description="NVHPC-based image loaded with necessary dependencies for building HLM/HLM-FATES images"
... 
